version: '1'
services:
  authapp:
    container_name: authapp
    image: authapp:1.0.0
    build: ./authapp
    ports:
      - 8080:8080
    restart: on-failure
    volumes:
      - auth:/usr/src/app/
    networks:
      - fullstack


  fetchapp:
    container_name: fetchapp
    image: fetchapp:1.0.0
    build: ./fetchapp
    ports:
      - 5000:5000
    networks:
      - fullstack

volumes:
  auth:

networks:
  fullstack:
    driver: bridge